### ISSUE TITLE
Link to GC Lignano Golfsuite - REALLY URGENT

### ISSUE THREAD

**Issue by brValentina** [xtradesoft/nexxchange-teetime-widget#2]
Good morning, 
we have just personalized the GC Lignano widget and now we have to link it to the Lignano Golfsuite.
In the issuer we wrote "lignano-golf-club", but as you can see in the attached screenshot nothing appears.
Can you help us, please?
It is really **URGENT**.

Thank you for your reply.

Kind regards

Valentina

![schermata 2019-02-25 alle 12 09 15](https://user-images.githubusercontent.com/47458831/53333455-398a8380-38f6-11e9-80f4-66794d483204.png)

**Comment by romanxts** [comment]
http://golflignano.it/de/golf/green-fee-reservieren/ looks ok ... seems like some historic issue
